# Service for the PostgreSQL database
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DB
    ports:
      - 5432:5432
    # Expose port 5432 for accessing the database
